### ISSUE TITLE
JSON error in cameras.json

### ISSUE THREAD

**Issue by Cafun** [Christofo/sssAI#2]
Hi!
I'm trying your sssAi container, created the settings.json and the cameras.json (with Notepad ++), but when I start the sssAi container, it creates the following log:

2020-07-19T19:50:04.378513195Z Traceback (most recent call last):
2020-07-19T19:50:04.379568450Z   File "/run.py", line 9, in <module>
2020-07-19T19:50:04.379718228Z     from app.main import app
2020-07-19T19:50:04.379781154Z   File "/app/main.py", line 13, in <module>
2020-07-19T19:50:04.379847967Z     cameradata = json.load(f)
2020-07-19T19:50:04.379908556Z   File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
2020-07-19T19:50:04.379990470Z     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
2020-07-19T19:50:04.380054796Z   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
2020-07-19T19:50:04.380620793Z     return _default_decoder.decode(s)
2020-07-19T19:50:04.380825409Z   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
2020-07-19T19:50:04.381359606Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2020-07-19T19:50:04.381619948Z   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
2020-07-19T19:50:04.381996354Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2020-07-19T19:50:04.382135094Z json.decoder.JSONDecodeError: Expecting value: line 6 column 30 (char 109).

My cameras.json looks like this:

{
    "1":
        {
        "name": "Oprit",
        "threshold": 50,
        "triggerUrl": https://xxx.xxx.xxx.xxx:xxx/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method="Incoming"&version=1&token=xxxxxxx
        }
}

I hope you can help me with this.

Also one more question:
In the settings.json there is a username/password, but I can't find for what the username/password is. I can only think it's for DeepStack. Is that it?

**Comment by jrendell** [comment]
> "triggerUrl": [https://xxx.xxx.xxx.xxx:xxx/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method="Incoming"&version=1&token=xxxxxxx]

Remove the double quotes around "Incoming" so it is ...&method=Incoming&version.....

> Also one more question:
> In the settings.json there is a username/password, but I can't find for what the username/password is. I can only think it's for DeepStack. Is that it?

It is used in the url to make a call to Surveillance Station, so it should be the password for SS.  In my testing however it has not mattered what I put in those fields.

**Comment by Cafun** [comment]
Removing the double quotes around "Incoming" didn't helped. This was a 1:1 copy of the action trigger in SS.
But thanks for your reply.

**Comment by jrendell** [comment]
Did you restart the container after making the change?
As listed in the reddit thread, if you copy the SS url Synology injects the double quote around Incoming.  Those quotes have to be removed.

**Comment by Cafun** [comment]
Yes I did.
I was just looking in the Reddit thread. And indeed, the quotes needs to be removed around Incoming, but what I did, I removed it from the whole URL.
So, now that error is resolved, thnx.

Now I need to troubleshoot another error I'm getting.
Thanks for your help!
